name: Setup Environment
description: 'Setup environment'

runs:
  using: "composite"
  steps:
    - name: Install JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install project dependencies
      shell: bash
      run: flutter pub get
