name: build web

on:
  push:
    branches: [master] # Just in case master was not up to date while merging PR
  pull_request:
    types: [opened, synchronize]

jobs:
  build_web:
    name: Build web-app
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up flutter beta
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Enable flutter web
        run: flutter config --enable-web

      - name: Run pub get
        run: flutter pub get

      - name: Build web
        run: flutter build web
